export const Routes = {
	HOME: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	FORGOT_PASSWORD: '/forgot_password',
	RESET_PASSWORD: '/reset_password',
	PROFILE: '/profile',
	EDIT_PROFILE: '/profile/edit',
	ORDERS: '/profile/orders',
	PROFILE_ORDER_INFO: '/profile/orders/:number',
	INGREDIENT: '/ingredients/:id',
	FEED: '/feed',
	FEED_ORDER_INFO: '/feed/:number',
	NOT_FOUND: '*',
};
